---
title: "Untitled"
format:
  revealjs:
    incremental: true
editor: visual
---

# Background

## Terms

-   statin

-   ezetimibe

-   aherosclerotic cardiovascular disease (ASCVD)

## Before Research

-   need research between statin with ezetimibe and monothrapy of statin

-   focus on randomised, long term(\>1year)

-   expect statin with ezetimbie therapy more efficency and safety

# Methods

## Study Design

-   using institutional review board

-   no major protocol change regarding sample size, study population, clinical endpoint

-   no planned discontinuation rules

-   reviewed investigational data at exact intervals for accurancy and completeness

-   The data and safety monitoring board (DSMB) for safety and evaluate progress

## Participants

-   patients with documented ASCVD requiring high-intensity statin therapy

-   Documented ASCVD

    -   myocardial infarction (MI): 심근경색

    -   acute coronary syndrome: 급성 관상동맥 증후군

    -   history of coronary revascularisation or other arterial revascularisation procedures: 관상 동맥 재관류 시술 이력

    -   ischaemic stroke: 허혈성 뇌졸중

    -   peripheral artery disease (PAD): 말초동맥 질환

## Randomisation

-   randomly assigned using web-response permuted-block randomisation

-   stratified by LDL less than 100mg/dL and diabetes

-   computer generated by external programmer (not associated with this research)

## Procedures

## Outcomes

## Statistical analysis

# Results

# Discussion
